INSERT INTO Health_Fund(name, description, active, version) values('ACA', 'ACA Health Benefits Fund', TRUE, 0);
INSERT INTO Health_Fund(name, description, active, version) values('ahm', 'ahm health insurance', TRUE, 0);
INSERT INTO Health_Fund(name, description, active, version) values('AIA', 'AIA Health Insurance Pty Ltd', TRUE, 0);
INSERT INTO Health_Fund(name, description, active, version) values('Australian Unity', 'Australian Unity Health Limited', TRUE, 0);
INSERT INTO Health_Fund(name, description, active, version) values('Bupa', 'Bupa HI Pty Ltd', TRUE, 0);
INSERT INTO Health_Fund(name, description, active, version) values('CBC Corporate Health', 'CBHS Corporate Health Pty Ltd', TRUE, 0);
INSERT INTO Health_Fund(name, description, active, version) values('CBH Health', 'CBHS Health Fund Limited', TRUE, 0);
INSERT INTO Health_Fund(name, description, active, version) values('CDH Benefits', 'CDH Benefits Fund', TRUE, 0);
INSERT INTO Health_Fund(name, description, active, version) values('CUA Health', 'CUA Health Limited', TRUE, 0);
INSERT INTO Health_Fund(name, description, active, version) values('Defence Health', 'Defence Health Limited', TRUE, 0);
INSERT INTO Health_Fund(name, description, active, version) values('Doctors Health', 'Doctors Health', TRUE, 0);
INSERT INTO Health_Fund(name, description, active, version) values('GMHBA', 'GMHBA Limited', TRUE, 0);
INSERT INTO Health_Fund(name, description, active, version) values('GU Health', 'GU Health', TRUE, 0);
INSERT INTO Health_Fund(name, description, active, version) values('HBF', 'HBF Health Limited', TRUE, 0);
INSERT INTO Health_Fund(name, description, active, version) values('HCF', 'HCF', TRUE, 0);
INSERT INTO Health_Fund(name, description, active, version) values('Health Care Insurance', 'Health Care Insurance Limited', TRUE, 0);
INSERT INTO Health_Fund(name, description, active, version) values('Health Insurance Fund', 'Health Insurance Fund of Australia Limited', TRUE, 0);
INSERT INTO Health_Fund(name, description, active, version) values('Health Partners', 'Health Partners', TRUE, 0);
INSERT INTO Health_Fund(name, description, active, version) values('health.com.au', 'health.com.au', TRUE, 0);
INSERT INTO Health_Fund(name, description, active, version) values('Latrobe Health', 'Latrobe Health Services', TRUE, 0);
INSERT INTO Health_Fund(name, description, active, version) values('Medibank', 'Medibank Private Limited', TRUE, 0);
INSERT INTO Health_Fund(name, description, active, version) values('Mildura Health', 'Mildura Health Fund', TRUE, 0);
INSERT INTO Health_Fund(name, description, active, version) values('National Health Benefits', 'National Health Benefits Australia Pty Ltd (onemedifund)', TRUE, 0);
INSERT INTO Health_Fund(name, description, active, version) values('Navy Health', 'Navy Health Ltd', TRUE, 0);
INSERT INTO Health_Fund(name, description, active, version) values('nib', 'nib Health Funds Ltd.', TRUE, 0);
INSERT INTO Health_Fund(name, description, active, version) values('Nurses & Midwives Health', 'Nurses & Midwives Health', TRUE, 0);
INSERT INTO Health_Fund(name, description, active, version) values('Peoplecare Health', 'Peoplecare Health Insurance', TRUE, 0);
INSERT INTO Health_Fund(name, description, active, version) values('Phoenix Health', 'Phoenix Health Fund Limited', TRUE, 0);
INSERT INTO Health_Fund(name, description, active, version) values('Police Health', 'Police Health', TRUE, 0);
INSERT INTO Health_Fund(name, description, active, version) values('Queensland Country Health', 'Queensland Country Health Fund Ltd', TRUE, 0);
INSERT INTO Health_Fund(name, description, active, version) values('Railway and Transport Health', 'Railway and Transport Health Fund Limited', TRUE, 0);
INSERT INTO Health_Fund(name, description, active, version) values('Reserve Bank Health', 'Reserve Bank Health Society Ltd', TRUE, 0);
INSERT INTO Health_Fund(name, description, active, version) values('St.Lukes Health', 'St.Lukes Health', TRUE, 0);
INSERT INTO Health_Fund(name, description, active, version) values('Teachers Health', 'Teachers Health', TRUE, 0);
INSERT INTO Health_Fund(name, description, active, version) values('Transport Health', 'Transport Health Pty Ltd', TRUE, 0);
INSERT INTO Health_Fund(name, description, active, version) values('TUH Health', 'TUH Health Fund', TRUE, 0);
INSERT INTO Health_Fund(name, description, active, version) values('Westfund', 'Westfund Limited', TRUE, 0);